services:
  desktop:
    image: ghcr.io/matsuolab/virtual_desktop:latest
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - DISPLAY
    ports:
      - "${WEB_PORT}:6080"
    volumes: 
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
    security_opt:
      - seccomp:unconfined
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  omnigibson:
    build:
      context: docker
      dockerfile: Dockerfile
    runtime: nvidia
    depends_on:
      - desktop
    volumes: 
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - DISPLAY
    ports:
     - "8000:8000"
    entrypoint: ["/bin/bash","-lc","tail -f /dev/null"]